feat(WIP bulk remove): bulk remove datasets
qri-io/desktop pull request #644
Opened 2020-10-08 17:44 UTC by uhLeeshUh

All of the bulk remove logic is working right now except in the case where a user tries to remove a single dataset by checking its checkbox and clicking the bulk "Remove" action button (as opposed to clicking the kabob menu on that dataset row and clicking the "Remove" option there). This is because of a design decision I made which I am now questioning around whether the remove action should be owned fully by the `RemoveDataset` modal or if it should be passed as a prop to the modal from the call site of the "Remove" button.

Backing up a sec to make this clearer, the design questions I asked myself were:

1. **Should the `RemoveDataset` modal be shared for removing a single dataset & multiple datasets?** My answer is yes because the UI is almost identical and the only switchable piece we'd need to make that work is the modal's `onSubmit` function which would either remove one or multiple datasets
2. **If the modal is shared, where should those `onSubmit` functions come from?** I decided to have them be sent as a prop to the modal [here](https://github.com/qri-io/desktop/compare/au/bulk-remove-action?expand=1#diff-635208e2ec68f1526f806d00d9ab0f5dR26) (via kabob menu) and [here](https://github.com/qri-io/desktop/compare/au/bulk-remove-action?expand=1#diff-05d5643c1feb402fb0c4dc241a47c69aR129) (via bulk Remove button) because in the case of a bulk action, we have the added requirement of disabling the button while the bulk action is running and that can only happen by closing over the `DatasetList` component's state setter for `bulkActionExecuting` as is happening [here](https://github.com/qri-io/desktop/compare/au/bulk-remove-action?expand=1#diff-05d5643c1feb402fb0c4dc241a47c69aR110). The issue I'm running into now, however, is that the two different `onSubmit` functions take differently structured params (the fn to remove an individual dataset takes a list of params whereas the fn to bulk remove expects an [array](https://github.com/qri-io/desktop/compare/au/bulk-remove-action?expand=1#diff-d66cdf4c0e1836971ac5f7cdcd53e1a0R678)) and the assumption I make [here](https://github.com/qri-io/desktop/compare/au/bulk-remove-action?expand=1#diff-c662b20f15225e0f651d2b2798629b85R46-R48) to correctly format those params is failing when the `onSubmit` for bulk actions is being sent with only a single dataset to remove.

Coming up for some air here, I'm wondering if any of these ideas feel best as a solution?
- refactor the params to the removeDatasetAndFetch action to also be an array, but I don't like this option because it breaks the pattern we typically have for non-bulk actions of accepting a list of params
- have `RemoveDataset` handle choosing which `onSubmit` function to use based on the number of datasets. This is my preferred choice, but then I run into the issue of not being able to control the `bulkActionExecuting` state in `DatasetList`

2020-10-08 17:47 UTC, uhLeeshUh commented on app/components/collection/collectionHome/DatasetList.tsx
> -  // use memoization to theoretically speed up rendering for example:
@b5 I ended up removing this memoization logic since I noticed a bug with it where when a user selects a dataset => then types in filter text =>  then removes that filter text => now the original dataset has its checkbox selected but the bulk action buttons aren't present

2020-10-08 17:50 UTC, b5 commented on app/components/collection/collectionHome/DatasetList.tsx
> -  // use memoization to theoretically speed up rendering for example:
hrm, ok I guess we'll have to save it for another pass. The lag on building selections is not great, but I agree having things slow and working is better than having things fast and broken

2020-10-08 17:54 UTC, uhLeeshUh commented on app/components/modals/RemoveDataset.tsx
> +  const isLinked = !!datasets.find(dataset => dataset.fsiPath)
I made the design decision here to show the checkbox to keep files if any of the selected datasets is linked to the file system. The action to keep files will be an all-or-nothing one for the full group of datasets, with only the ones with an `fsiPath` actually having any action taken to remove the files

2020-10-08 18:03 UTC, b5 commented on app/components/modals/RemoveDataset.tsx
> +  const isLinked = !!datasets.find(dataset => dataset.fsiPath)
into it. good choice 😄

2020-10-08 18:20 UTC, b5 commented
I think the answer to your question is to modify the signature of the function passed as the `OnSubmit` prop to the `RemoveDataset`, to make it more opaque, going from this:
```ts
export interface RemoveDatasetModal {
   // ..
   onSubmit: (...args: any) => any
}
```

to this:
```ts
export interface RemoveDatasetModal {
   // ..
   onSubmit: () => Promise<AnyAction>
}
```

you're already doing this wrapping inside the `handleSubmit` function of `RemoveDataset`, by moving it out into user land and requiring callers pass an opaque function that returns a promise, you can push configuration up to the call site, while retaining the requirement that the `onSubmit` prop  return a  promise so you can `await onSubmit()`

2020-10-08 18:24 UTC, b5 commented
As for the principle problem you were having of a single checkbox bulk action, a set of 1 is still a set, and we should consider it a bulk action even though it's a single dataset. The fact that the same modal handles both singular and bulk (set-oriented) actions is a coincidence

2020-10-08 18:39 UTC, uhLeeshUh commented
@b5 along the lines of treating a set of 1 as still a set, do you have advice for differentiating how to correctly pass args to the `onSubmit` function [here](https://github.com/qri-io/desktop/pull/644/files#diff-c662b20f15225e0f651d2b2798629b85R46-R51)? The problem I've encountered is I don't have a reliable way of knowing if the single dataset to be removed was sent to the modal via the kabob menu or the bulk action button (this check of just "is there only one dataset" isn't sufficient). If via the kabob, I need to pass the args as a list to the `onSubmit` fn to match up with removeDatasetAndFetch, but if via the bulk action, then I treat it as the "set of one" approach and pass in an array to satisfy removeDatasetsAndFetch.

2020-10-08 18:53 UTC, b5 commented
I'm saying build the `onSubmit` function before this handler is ever called, and pass it to `RemoveDataset`. You've got the problem figured out:

>  The problem I've encountered is I don't have a reliable way of knowing if the single dataset to be removed was sent to the modal via the kabob menu or the bulk action button

That's because this info is owned by the caller. So keep the `RemoveDataset` modal dumb and make it's `onSubmit` prop a function that the caller has to construct.

2020-10-08 19:15 UTC, uhLeeshUh commented
Ahhh gotcha. The only thing we'll need from the handler is the `keepFiles` value then but we can close over the other values in the correct format. Ok cool! I'll give that a go now

2020-10-09 01:54 UTC, ramfox requested changes
Looks great! Love love love the tests & the util function. It's definitely made me realize some stuff we can refactor in the e2e tests :)

I have some strong opinions about what types we should be using for the bulk actions, especially since we are trying to generalize some of the work so it can be used for multiple kinds of bulk actions! Basically, I think we should be using `VersionInfo[]`s everywhere, since that is the data type we start with and is the most general we will ever need to be for any actions we need to do.

2020-10-09 01:54 UTC, ramfox commented on app/components/modals/RemoveDataset.tsx
> +            {isDeletingSessionUserDataset && <div className='warning'>Warning: removing a dataset which belongs to you means you cannot return to that dataset&apos;s history.</div>}
how do we feel about changing this text from

"a dataset which belongs to you"
to
"a dataset that you created"

2020-10-09 01:54 UTC, ramfox commented on app/components/collection/collectionHome/TableRowHamburger.tsx
> +  removeDatasetAndFetch: (...args: Parameters<typeof removeDatasetAndFetch>) => Promise<AnyAction>
I like this syntax! 

On one hand, I don't like that you can't just glance at the props to understand what the function is expecting, but on the other hand it means we are ensuring the function has the parameters we are expecting & its one fewer place to change if something about the action changes.

Plus, we all have IDE's that will be able to give us quick looks into what parameter's the action is expecting.

2020-10-09 01:54 UTC, ramfox commented on app/components/collection/collectionHome/DatasetList.tsx
> +  const handleBulkActionForDatasets = async (actionType: DatasetActionType, actionGerund: string, actionPastTense: string, action: DatasetAction, refs: Array<{username: string, name: string, isLinked
we aren't using `keepFiles` here, I think we should remove it!

2020-10-09 01:54 UTC, ramfox commented on app/components/collection/collectionHome/DatasetList.tsx
> +        datasets: selected.map(ds => ({ username: ds.username, name: ds.name, fsiPath: ds.fsiPath })),
I think we should be moving around `VersionInfo`s rather than a new datatype! Let's just pass the list of selected VersionInfos, and then push the `selected`

And if we are trying to use a generalized `handleBulkActionForDataset` it should probably take `VersionInfo`s instead of `QriRefs` because qriRefs will only give us the barest of information. This means that we would also have to adjust the `pullDatasets` API function to take `VersionInfo[]` as well, & adjust the definition of a `DatasetAction` in this file.

2020-10-09 01:54 UTC, ramfox commented on app/components/collection/collectionHome/DatasetList.tsx
> +  const handleBulkActionForDatasets = async (actionType: DatasetActionType, actionGerund: string, actionPastTense: string, action: DatasetAction, refs: Array<{username: string, name: string, isLinked
I write somewhere below that I think we should be passing around `VersionInfo`s, not new types here, if so, we should change the `Array<{...}>` to `VersionInfo[]`

2020-10-09 01:54 UTC, ramfox commented on app/components/collection/collectionHome/DatasetList.tsx
> +    const refs = selected.map(ds => ({ username: ds.username, name: ds.name, isLinked: !!ds.fsiPath, keepFiles }))
as stated below (or whatever order these comments appear in) I think we should be passing around `VersionInfos` rather than new types, just pass `selected` into refs.

2020-10-09 01:54 UTC, ramfox commented on app/components/collection/collectionHome/DatasetList.tsx
> +    const refs = selected.map(qriRefFromVersionInfo)
same comment as below, let's just use `VersionInfo` for all these bulk functions.

2020-10-09 01:54 UTC, ramfox commented on app/components/collection/collectionHome/DatasetList.tsx
> +    const refs = selected.map(ds => ({ username: ds.username, name: ds.name, isLinked: !!ds.fsiPath, keepFiles }))
also it looks like `isLinked` is getting calculated in the `RemoveModal` so we don't have to worry about losing any data by turning this into a `VerisonInfo`

2020-10-09 01:54 UTC, ramfox commented on app/models/modals.ts
> +  datasets: Array<{ username: string, name: string, fsiPath?: string }>
Think this should be `VersionInfo[]`

2020-10-09 02:17 UTC, ramfox commented
Another note, I don't think your tests will pass until the `rename` pr is merged, I had to do a lot of finessing on tests that relied on elements that had changed! But the tests that you added definitely work.

2020-10-09 12:49 UTC, uhLeeshUh commented on app/components/collection/collectionHome/TableRowHamburger.tsx
> +  removeDatasetAndFetch: (...args: Parameters<typeof removeDatasetAndFetch>) => Promise<AnyAction>
sweet! Yeah I'm a big fan of it as well because it makes keep track of changed types a lot easier

2020-10-09 12:53 UTC, uhLeeshUh commented
Oh yeah @ramfox nice idea to simplify the passed action type to `VersionInfo` -- I was finding it hard to keep track of those two similar types and think `VersionInfo` as a used pattern for all our actions is great

2020-10-09 13:13 UTC, uhLeeshUh commented on app/components/collection/collectionHome/DatasetList.tsx
> +    const refs = selected.map(ds => ({ username: ds.username, name: ds.name, isLinked: !!ds.fsiPath, keepFiles }))
Hmm my only worry with taking away `isLinked` here is that the calculation in `RemoveDataset` is pretty basic (`isLinked` is true if any dataset in the set has an `fsiPath`) and I worry that in each individual `removeDataset` call that means we'd try to pass`keep-files` where it's not actually needed and it could error, right?

2020-10-09 14:25 UTC, uhLeeshUh commented on app/components/collection/collectionHome/DatasetList.tsx
> +    const actionCallback = async () => removeDatasetsAndFetch(selected, keepFiles)
@ramfox what do you think of this `actionCallback` pattern? I figured it was a way for us to still reuse the `handleBulkActionForDatasets` function but give both the `handleBulkRemove` and `handleBulkPull` handlers the ability to craft their own action callers (and in the case of remove, add `keepFiles` as the final arg)

2020-10-09 14:53 UTC, ramfox approved these changes
LGTM!!!

Nice :)

2020-10-09 14:53 UTC, ramfox commented on app/components/collection/collectionHome/DatasetList.tsx
> +    const actionCallback = async () => removeDatasetsAndFetch(selected, keepFiles)
I think this is great!

2020-10-09 14:58 UTC, merged