feat(RenameDataset): add `RenameDataset` modal and rename dataset button to dataset page
qri-io/desktop pull request #645
Opened 2020-10-08 19:27 UTC by ramfox

closes #637 

Still todo: e2e test fixes

2020-10-08 19:29 UTC, ramfox commented on app/components/collection/layouts/DatasetLayout.tsx
> +    }
I'm aware that it's odd that I added a RenameButton component for one task and an inline button creation for remove dataset, but my next pr is going to be to get much of these in a `hamburger` & I wanted to test out both options.

2020-10-08 19:37 UTC, b5 commented on app/components/collection/layouts/DatasetLayout.tsx
> +    }
this was my immediate question. thank you.

2020-10-09 13:16 UTC, chriswhong requested changes
This modal's input is styled differently from other modals and I think we should be consistent here.  The full red background on invalid input is also kind of biting, and suggest we make the outline of the input red and show the message in red.


Another suggestion:
- Instead of an action button where the other buttons are, just add a pencil icon to the right of the dataset name.  Rename isn't quite the same level of action as an export or push

We should also add rename to the hamburger menu in collection view.  I think adding a pencil icon to the dataset name would work here as well (versus the hamburger menu where the other actions live)


<img width="529" alt="Qri_Desktop" src="https://user-images.githubusercontent.com/1833820/95586655-fc153400-0a0e-11eb-9b01-e07f68af0b0e.png">

2020-10-09 14:50 UTC, b5 commented
> Instead of an action button where the other buttons are, just add a pencil icon to the right of the dataset name. Rename isn't quite the same level of action as an export or push

While I agree this might be nice, I'm not into the idea of adding a new UI convention until we've had a chance to think it through. To me the pencil icon implies that I'd be able to edit the dataset name _without_ a modal – editing the title directly in the `NavTopbar` component, which we've just done a bunch of work to move into a modal.

Renaming a dataset isn't–and shouldn't be–a common task. Let's push it into the hamburger menu & make the modal styling changes you've suggested

2020-10-09 17:57 UTC, ramfox commented on app/components/collection/layouts/DatasetLayout.tsx
> +    }
I can't express how much I hate this, hahaha.

So when I refactor the datasetlayout next I'm going to move this into its own button.

@b5  don't hate me! But I think it's this weird logic/state tree mush that we can push off into a button that should be able to be placed wherever, & won't clog up any parent components as this one is currently doing here.

2020-10-09 18:41 UTC, chriswhong approved these changes
🚀

2020-10-09 19:05 UTC, merged